### ISSUE TITLE
CTRL+Click not working and namespaces aren't found

### ISSUE THREAD

**Issue by burtonrhodes** [burtonrhodes/intellij-obsolete-plugins#2]
Repost from "Nikos Dimitrakas":
I tested it and looked at your changes. There seems to be something wrong though. CTRL+clicking is not working, and namespaces and action names are red (not found). I saw that you put the new DTD URL with http instead of https. Could that be causing the problem? 

Reference: [https://youtrack.jetbrains.com/issue/IDEA-303887](https://youtrack.jetbrains.com/issue/IDEA-303887)

**Comment by nikosdimitrakas** [comment]
Everything work now in 2023.2.2

**Comment by burtonrhodes** [comment]
@nikosdimitrakas Glad to hear it. And great catch on the https issue. Won't have been scratching my head on that one for a while. 

How does this version get pushed to the intellij website?

**Comment by burtonrhodes** [comment]
I will add this version to my PR of the parent branch, but not sure anyone is maintaining it.

**Comment by burtonrhodes** [comment]
Bug fixed in release v2023.2.2 #3
