### ISSUE TITLE
Make compatible with 2023.3.1

### ISSUE THREAD

**Issue by nikosdimitrakas** [burtonrhodes/intellij-obsolete-plugins#4]
The new version of IntelliJ IDEA does not like the plugin. I have figured out that it is the value of the attribute until-build in the idea-version element in the plugin.xml that is the problem. I manually changed the value to 233.* and the plugin works. The file plugin.xml is inside instrumented-struts2-2023.2.1.jar that is inside struts2-2023.2.1.zip
Could you do a new release with the new version numbers?

**Comment by burtonrhodes** [comment]
Upgrade completed.

[https://github.com/burtonrhodes/intellij-obsolete-plugins/releases/tag/v2023.3.2](https://github.com/burtonrhodes/intellij-obsolete-plugins/releases/tag/v2023.3.2)
